# Hugo site configuration

title = "Abigail Afi Gbadago"
theme = "not-much"
languageCode = "en-us"
baseURL = "https://abigailgbadago.vercel.app"
copyright = "Abigail Afi Gbadago © {year}"

[markup]
  [markup.highlight]
    style = 'dracula'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[params]
theme = "auto"
palette = "eink"
showThemeNotice = true
showPostsSummary = false

# Giscus Comment System
[params.giscus]
repository = "username/repository"
repositoryId = "repositoryId"
categoryName = "categoryName"
categoryId = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"
language = "en"
lazyLoading = true

# Navigation
[menu]
  [[menu.main]]
    identifier = "home"
    name = "home"
    title = "Home"
    url = "/"
    weight = 1
  
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/posts"
    weight = 3
  
  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "About"
    url = "/about"
    weight = 2
  
  [[menu.main]]
    identifier = "tags"
    name = "tags"
    title = "tags"
    url = "baseURL/tags"
    weight = 4

  [[menu.main]]
    identifier = "github"
    name = "github"
    title = "GitHub"
    url = "https://github.com/AfiMaameDufie"
    weight = 5